backend:
  name: git-gateway
  branch: master
media_folder: themes/PaperModX/assets/img
public_folder: /img
collections:
  - name: 'tags'
    label: 'Categories'
    folder: 'content/tags'
    create: true
    slug: '{{name}}'
    identifier_field: 'name'
    summary: '{{name}}'
    fields:
      - {name: 'name', label: 'Name'}

  - name: 'blog'
    label: 'Blog'
    folder: 'content/blog'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - name: 'tags'
        label: 'Tags'
        widget: 'relation'
        collection: 'tags'
        search_fields: ['name']
        value_field: 'name'
        display_fields: ['name']
        multiple: true
        required: false
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }